# Virtual workspace
# https://docs.swmansion.com/scarb/docs/reference/workspaces.html#virtual-workspace

[workspace]
members = ["dojo"]

[workspace.package]
version = "1.3.6"
edition = "2024_07"

#--------------------------
# Dojo profiles declaration
#
[profile.dev]
[profile.slot]
[profile.staging]
[profile.sepolia]
[profile.mainnet]
