kind = "DojoModel"
class_hash = "0x2a9e6b7d401e8c9fa77e5221dce4f049334ce8ed4d7a53f88adf72b3af968eb"
original_class_hash = "0x2a9e6b7d401e8c9fa77e5221dce4f049334ce8ed4d7a53f88adf72b3af968eb"
abi = "manifests/slot/base/abis/models/origami_token-ERC20MetadataModel-3368c0e3.json"
tag = "origami_token-ERC20MetadataModel"
manifest_name = "origami_token-ERC20MetadataModel-3368c0e3"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "decimals"
type = "u8"
key = false

[[members]]
name = "total_supply"
type = "u256"
key = false
