kind = "DojoModel"
class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
original_class_hash = "0x290d67abdcfd26f1d9768cec5ff48842cd405ce33417c6e8a212da0baa77e86"
abi = "manifests/dev/base/abis/models/origami_token-ERC721TokenApprovalModel-560d5854.json"
tag = "origami_token-ERC721TokenApprovalModel"
manifest_name = "origami_token-ERC721TokenApprovalModel-560d5854"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
