kind = "DojoModel"
class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
original_class_hash = "0x356e5dea0e7529f6c2617074b151c03b23cfb408d0a1ef8e123c226502cf115"
abi = "manifests/dev/base/abis/models/origami_token-ERC721OwnerModel-61577880.json"
tag = "origami_token-ERC721OwnerModel"
manifest_name = "origami_token-ERC721OwnerModel-61577880"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "address"
type = "ContractAddress"
key = false
