kind = "DojoModel"
class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
original_class_hash = "0xf5a9baf34c431fc11c05e15ddff7eb4750847ada1db57528ddad2966a7f3ec"
abi = "manifests/dev/base/abis/models/origami_token-ERC721EnumerableTokenModel-5c383d9f.json"
tag = "origami_token-ERC721EnumerableTokenModel"
manifest_name = "origami_token-ERC721EnumerableTokenModel-5c383d9f"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "token_id"
type = "u128"
key = true

[[members]]
name = "index"
type = "u128"
key = false
