kind = "DojoModel"
class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
original_class_hash = "0x43c7452e01d3ecb9f7460490397bd17c0d3461bd322d93bbfac4925dc9ee1ed"
abi = "manifests/staging/base/abis/models/origami_token-InitializableModel-5c624096.json"
tag = "origami_token-InitializableModel"
qualified_path = "origami_token::components::security::initializable::initializable_model"
manifest_name = "origami_token-InitializableModel-5c624096"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false
